/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AssessmentCommonRouteImport } from './routes/assessment.common'
import { Route as AssessmentSportRouteImport } from './routes/assessment.sport'
import { Route as AthleteDashboardRouteImport } from './routes/athlete.dashboard'
import { Route as AthleteFitnessDnaRouteImport } from './routes/athlete.fitness-dna'
import { Route as AthleteGoalsRouteImport } from './routes/athlete.goals'
import { Route as AthleteHealthRouteImport } from './routes/athlete.health'
import { Route as AthleteNutritionRouteImport } from './routes/athlete.nutrition'
import { Route as AthletePassportRouteImport } from './routes/athlete.passport'
import { Route as AthletePerformanceRouteImport } from './routes/athlete.performance'
import { Route as AthleteProgramRouteImport } from './routes/athlete.program'
import { Route as AthleteRecoveryRouteImport } from './routes/athlete.recovery'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachAssistantRouteImport } from './routes/coach.assistant'
import { Route as CoachAthletesRouteImport } from './routes/coach.athletes'
import { Route as CoachAttentionRouteImport } from './routes/coach.attention'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as CoachNutritionRouteImport } from './routes/coach.nutrition'
import { Route as CoachPerformanceRouteImport } from './routes/coach.performance'
import { Route as CoachProfileRouteImport } from './routes/coach.profile'
import { Route as CoachProgramsRouteImport } from './routes/coach.programs'
import { Route as CoachAthleteIdRouteImport } from './routes/coach.athlete.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCommonRoute = AssessmentCommonRouteImport.update({
  id: '/assessment/common',
  path: '/assessment/common',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentSportRoute = AssessmentSportRouteImport.update({
  id: '/assessment/sport',
  path: '/assessment/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteDashboardRoute = AthleteDashboardRouteImport.update({
  id: '/athlete/dashboard',
  path: '/athlete/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteFitnessDnaRoute = AthleteFitnessDnaRouteImport.update({
  id: '/athlete/fitness-dna',
  path: '/athlete/fitness-dna',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteGoalsRoute = AthleteGoalsRouteImport.update({
  id: '/athlete/goals',
  path: '/athlete/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteHealthRoute = AthleteHealthRouteImport.update({
  id: '/athlete/health',
  path: '/athlete/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteNutritionRoute = AthleteNutritionRouteImport.update({
  id: '/athlete/nutrition',
  path: '/athlete/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePassportRoute = AthletePassportRouteImport.update({
  id: '/athlete/passport',
  path: '/athlete/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletePerformanceRoute = AthletePerformanceRouteImport.update({
  id: '/athlete/performance',
  path: '/athlete/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteProgramRoute = AthleteProgramRouteImport.update({
  id: '/athlete/program',
  path: '/athlete/program',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteRecoveryRoute = AthleteRecoveryRouteImport.update({
  id: '/athlete/recovery',
  path: '/athlete/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAssistantRoute = CoachAssistantRouteImport.update({
  id: '/coach/assistant',
  path: '/coach/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAthletesRoute = CoachAthletesRouteImport.update({
  id: '/coach/athletes',
  path: '/coach/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAttentionRoute = CoachAttentionRouteImport.update({
  id: '/coach/attention',
  path: '/coach/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/coach/exercises',
  path: '/coach/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachNutritionRoute = CoachNutritionRouteImport.update({
  id: '/coach/nutrition',
  path: '/coach/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachPerformanceRoute = CoachPerformanceRouteImport.update({
  id: '/coach/performance',
  path: '/coach/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProfileRoute = CoachProfileRouteImport.update({
  id: '/coach/profile',
  path: '/coach/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramsRoute = CoachProgramsRouteImport.update({
  id: '/coach/programs',
  path: '/coach/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachAthleteIdRoute = CoachAthleteIdRouteImport.update({
  id: '/coach/athlete/$id',
  path: '/coach/athlete/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/assessment/common': typeof AssessmentCommonRoute
  '/assessment/sport': typeof AssessmentSportRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/fitness-dna': typeof AthleteFitnessDnaRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/health': typeof AthleteHealthRoute
  '/athlete/nutrition': typeof AthleteNutritionRoute
  '/athlete/passport': typeof AthletePassportRoute
  '/athlete/performance': typeof AthletePerformanceRoute
  '/athlete/program': typeof AthleteProgramRoute
  '/athlete/recovery': typeof AthleteRecoveryRoute
  '/coach/assistant': typeof CoachAssistantRoute
  '/coach/athletes': typeof CoachAthletesRoute
  '/coach/attention': typeof CoachAttentionRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/performance': typeof CoachPerformanceRoute
  '/coach/profile': typeof CoachProfileRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/assessment/common': typeof AssessmentCommonRoute
  '/assessment/sport': typeof AssessmentSportRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/fitness-dna': typeof AthleteFitnessDnaRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/health': typeof AthleteHealthRoute
  '/athlete/nutrition': typeof AthleteNutritionRoute
  '/athlete/passport': typeof AthletePassportRoute
  '/athlete/performance': typeof AthletePerformanceRoute
  '/athlete/program': typeof AthleteProgramRoute
  '/athlete/recovery': typeof AthleteRecoveryRoute
  '/coach/assistant': typeof CoachAssistantRoute
  '/coach/athletes': typeof CoachAthletesRoute
  '/coach/attention': typeof CoachAttentionRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/performance': typeof CoachPerformanceRoute
  '/coach/profile': typeof CoachProfileRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/assessment/common': typeof AssessmentCommonRoute
  '/assessment/sport': typeof AssessmentSportRoute
  '/athlete/dashboard': typeof AthleteDashboardRoute
  '/athlete/fitness-dna': typeof AthleteFitnessDnaRoute
  '/athlete/goals': typeof AthleteGoalsRoute
  '/athlete/health': typeof AthleteHealthRoute
  '/athlete/nutrition': typeof AthleteNutritionRoute
  '/athlete/passport': typeof AthletePassportRoute
  '/athlete/performance': typeof AthletePerformanceRoute
  '/athlete/program': typeof AthleteProgramRoute
  '/athlete/recovery': typeof AthleteRecoveryRoute
  '/coach/assistant': typeof CoachAssistantRoute
  '/coach/athletes': typeof CoachAthletesRoute
  '/coach/attention': typeof CoachAttentionRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/nutrition': typeof CoachNutritionRoute
  '/coach/performance': typeof CoachPerformanceRoute
  '/coach/profile': typeof CoachProfileRoute
  '/coach/programs': typeof CoachProgramsRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/athlete/$id': typeof CoachAthleteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/assessment/common'
    | '/assessment/sport'
    | '/athlete/dashboard'
    | '/athlete/fitness-dna'
    | '/athlete/goals'
    | '/athlete/health'
    | '/athlete/nutrition'
    | '/athlete/passport'
    | '/athlete/performance'
    | '/athlete/program'
    | '/athlete/recovery'
    | '/coach/assistant'
    | '/coach/athletes'
    | '/coach/attention'
    | '/coach/exercises'
    | '/coach/nutrition'
    | '/coach/performance'
    | '/coach/profile'
    | '/coach/programs'
    | '/coach/'
    | '/coach/athlete/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/assessment/common'
    | '/assessment/sport'
    | '/athlete/dashboard'
    | '/athlete/fitness-dna'
    | '/athlete/goals'
    | '/athlete/health'
    | '/athlete/nutrition'
    | '/athlete/passport'
    | '/athlete/performance'
    | '/athlete/program'
    | '/athlete/recovery'
    | '/coach/assistant'
    | '/coach/athletes'
    | '/coach/attention'
    | '/coach/exercises'
    | '/coach/nutrition'
    | '/coach/performance'
    | '/coach/profile'
    | '/coach/programs'
    | '/coach'
    | '/coach/athlete/$id'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/login'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/assessment/common'
    | '/assessment/sport'
    | '/athlete/dashboard'
    | '/athlete/fitness-dna'
    | '/athlete/goals'
    | '/athlete/health'
    | '/athlete/nutrition'
    | '/athlete/passport'
    | '/athlete/performance'
    | '/athlete/program'
    | '/athlete/recovery'
    | '/coach/assistant'
    | '/coach/athletes'
    | '/coach/attention'
    | '/coach/exercises'
    | '/coach/nutrition'
    | '/coach/performance'
    | '/coach/profile'
    | '/coach/programs'
    | '/coach/'
    | '/coach/athlete/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  AssessmentCommonRoute: typeof AssessmentCommonRoute
  AssessmentSportRoute: typeof AssessmentSportRoute
  AthleteDashboardRoute: typeof AthleteDashboardRoute
  AthleteFitnessDnaRoute: typeof AthleteFitnessDnaRoute
  AthleteGoalsRoute: typeof AthleteGoalsRoute
  AthleteHealthRoute: typeof AthleteHealthRoute
  AthleteNutritionRoute: typeof AthleteNutritionRoute
  AthletePassportRoute: typeof AthletePassportRoute
  AthletePerformanceRoute: typeof AthletePerformanceRoute
  AthleteProgramRoute: typeof AthleteProgramRoute
  AthleteRecoveryRoute: typeof AthleteRecoveryRoute
  CoachAssistantRoute: typeof CoachAssistantRoute
  CoachAthletesRoute: typeof CoachAthletesRoute
  CoachAttentionRoute: typeof CoachAttentionRoute
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachNutritionRoute: typeof CoachNutritionRoute
  CoachPerformanceRoute: typeof CoachPerformanceRoute
  CoachProfileRoute: typeof CoachProfileRoute
  CoachProgramsRoute: typeof CoachProgramsRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachAthleteIdRoute: typeof CoachAthleteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/common': {
      id: '/assessment/common'
      path: '/assessment/common'
      fullPath: '/assessment/common'
      preLoaderRoute: typeof AssessmentCommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/sport': {
      id: '/assessment/sport'
      path: '/assessment/sport'
      fullPath: '/assessment/sport'
      preLoaderRoute: typeof AssessmentSportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/dashboard': {
      id: '/athlete/dashboard'
      path: '/athlete/dashboard'
      fullPath: '/athlete/dashboard'
      preLoaderRoute: typeof AthleteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/fitness-dna': {
      id: '/athlete/fitness-dna'
      path: '/athlete/fitness-dna'
      fullPath: '/athlete/fitness-dna'
      preLoaderRoute: typeof AthleteFitnessDnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/goals': {
      id: '/athlete/goals'
      path: '/athlete/goals'
      fullPath: '/athlete/goals'
      preLoaderRoute: typeof AthleteGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/health': {
      id: '/athlete/health'
      path: '/athlete/health'
      fullPath: '/athlete/health'
      preLoaderRoute: typeof AthleteHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/nutrition': {
      id: '/athlete/nutrition'
      path: '/athlete/nutrition'
      fullPath: '/athlete/nutrition'
      preLoaderRoute: typeof AthleteNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/passport': {
      id: '/athlete/passport'
      path: '/athlete/passport'
      fullPath: '/athlete/passport'
      preLoaderRoute: typeof AthletePassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/performance': {
      id: '/athlete/performance'
      path: '/athlete/performance'
      fullPath: '/athlete/performance'
      preLoaderRoute: typeof AthletePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/program': {
      id: '/athlete/program'
      path: '/athlete/program'
      fullPath: '/athlete/program'
      preLoaderRoute: typeof AthleteProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete/recovery': {
      id: '/athlete/recovery'
      path: '/athlete/recovery'
      fullPath: '/athlete/recovery'
      preLoaderRoute: typeof AthleteRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/assistant': {
      id: '/coach/assistant'
      path: '/coach/assistant'
      fullPath: '/coach/assistant'
      preLoaderRoute: typeof CoachAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/athletes': {
      id: '/coach/athletes'
      path: '/coach/athletes'
      fullPath: '/coach/athletes'
      preLoaderRoute: typeof CoachAthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/attention': {
      id: '/coach/attention'
      path: '/coach/attention'
      fullPath: '/coach/attention'
      preLoaderRoute: typeof CoachAttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/coach/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/nutrition': {
      id: '/coach/nutrition'
      path: '/coach/nutrition'
      fullPath: '/coach/nutrition'
      preLoaderRoute: typeof CoachNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/performance': {
      id: '/coach/performance'
      path: '/coach/performance'
      fullPath: '/coach/performance'
      preLoaderRoute: typeof CoachPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/profile': {
      id: '/coach/profile'
      path: '/coach/profile'
      fullPath: '/coach/profile'
      preLoaderRoute: typeof CoachProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/programs': {
      id: '/coach/programs'
      path: '/coach/programs'
      fullPath: '/coach/programs'
      preLoaderRoute: typeof CoachProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/athlete/$id': {
      id: '/coach/athlete/$id'
      path: '/coach/athlete/$id'
      fullPath: '/coach/athlete/$id'
      preLoaderRoute: typeof CoachAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  AssessmentCommonRoute: AssessmentCommonRoute,
  AssessmentSportRoute: AssessmentSportRoute,
  AthleteDashboardRoute: AthleteDashboardRoute,
  AthleteFitnessDnaRoute: AthleteFitnessDnaRoute,
  AthleteGoalsRoute: AthleteGoalsRoute,
  AthleteHealthRoute: AthleteHealthRoute,
  AthleteNutritionRoute: AthleteNutritionRoute,
  AthletePassportRoute: AthletePassportRoute,
  AthletePerformanceRoute: AthletePerformanceRoute,
  AthleteProgramRoute: AthleteProgramRoute,
  AthleteRecoveryRoute: AthleteRecoveryRoute,
  CoachAssistantRoute: CoachAssistantRoute,
  CoachAthletesRoute: CoachAthletesRoute,
  CoachAttentionRoute: CoachAttentionRoute,
  CoachExercisesRoute: CoachExercisesRoute,
  CoachNutritionRoute: CoachNutritionRoute,
  CoachPerformanceRoute: CoachPerformanceRoute,
  CoachProfileRoute: CoachProfileRoute,
  CoachProgramsRoute: CoachProgramsRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachAthleteIdRoute: CoachAthleteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
